import json
import sys
import os

def generate_header():
    return """// ============================================================================
// AUTO-GENERATED CONFIGURATION FILE - DO NOT EDIT MANUALLY
// Generated by scripts/gen_config.py
// ============================================================================

#include "gpio_config.h"
#include <stddef.h>

"""

def generate_config(json_data):
    c_code = generate_header()
    c_code += "const sGpioPinConfig_t g_psGpioPinConfigs[] = {\n"

    for pin in json_data.get("pins", []):
        c_code += "    {\n"
        c_code += f'        .pcPinName = "{pin["name"]}",\n'
        
        # Direction
        direction = pin.get("direction", "INPUT")
        c_code += f'        .eDirection = GPIO_DIR_{direction},\n'
        
        # Pull
        pull = pin.get("pull", "NONE")
        c_code += f'        .ePull = GPIO_PULL_{pull},\n'
        
        # AVR Config
        if "avr" in pin:
            avr = pin["avr"]
            port_map = {"A": 0, "B": 1, "C": 2, "D": 3}
            port = avr.get("port", "B")
            # Handle string port "B" or int 1
            port_val = port_map.get(port, 0) if isinstance(port, str) else port
            
            c_code += "        #ifdef PLATFORM_AVR\n"
            c_code += f'        .u8AvrPort = {port_val}, // PORT{port}\n'
            c_code += f'        .u8AvrPin = {avr["pin"]},\n'
            c_code += "        #endif\n"

        # STM32 Config
        if "stm32" in pin:
            stm = pin["stm32"]
            port_map = {"A": 0, "B": 1, "C": 2}
            port = stm.get("port", "A")
            port_val = port_map.get(port, 0) if isinstance(port, str) else port
            
            c_code += "        #ifdef PLATFORM_STM32\n"
            c_code += f'        .u32Stm32Port = {port_val}, // GPIO{port}\n'
            c_code += f'        .u16Stm32Pin = {stm["pin"]},\n'
            c_code += f'        .u8Stm32Af = {stm.get("af", 0)},\n'
            c_code += "        #endif\n"
            
        # Arduino Config
        if "arduino" in pin:
            ard = pin["arduino"]
            c_code += "        #ifdef PLATFORM_ARDUINO\n"
            c_code += f'        .u8ArduinoPin = {ard["pin"]},\n'
            c_code += "        #endif\n"

        c_code += "    },\n"

    c_code += "    { .pcPinName = NULL } // Terminator\n"
    c_code += "};\n"
    return c_code

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python gen_config.py <input.json> [output.c]")
        sys.exit(1)

    json_path = sys.argv[1]
    
    # Optional output path, default to stdout
    output_file = None
    if len(sys.argv) >= 3:
        output_file = sys.argv[2]
        # Create directory if it doesn't exist
        os.makedirs(os.path.dirname(os.path.abspath(output_file)), exist_ok=True)

    try:
        with open(json_path, 'r') as f:
            data = json.load(f)
            c_content = generate_config(data)
            
            if output_file:
                with open(output_file, 'w') as out:
                    out.write(c_content)
                print(f"Generated {output_file}")
            else:
                print(c_content)
                
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)
