# Auto-generated by find_avr_toolchain.py - do not edit
set(AVR_GCC "C:/Program Files/WindowsApps/ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt/hardware/tools/avr/bin/avr-gcc.exe")
set(AVR_OBJCOPY "C:/Program Files/WindowsApps/ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt/hardware/tools/avr/bin/avr-objcopy.exe")
set(AVRDUDE "C:/Program Files/WindowsApps/ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt/hardware/tools/avr/bin/avrdude.exe")
set(AVRDUDE_CONF "C:/Program Files/WindowsApps/ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt/hardware/tools/avr/etc/avrdude.conf")
set(AVR_FROM_WINDOWSAPPS TRUE)
set(AVR_TOOLCHAIN_BASE "C:/Program Files/WindowsApps/ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt/hardware/tools/avr")
