// ============================================================================
// AUTO-GENERATED - DO NOT EDIT MANUALLY
// Generated by hal_embedded_mcp/scripts/gen_mcp_from_config.py
//
// MCP tool validation only (allowed pin names). Pin control uses
// gpio_config_gen.c (g_psGpioPinConfigs) from the same config.json.
// ============================================================================

#include <stddef.h>

const char *const g_apcMcpPinNames[] = {
    "LED1",
    "BUTTON1",
    NULL
};

const unsigned int g_u32McpPinCount = 2;