// ============================================================================
// AUTO-GENERATED CONFIGURATION FILE - DO NOT EDIT MANUALLY
// Generated by scripts/gen_config.py
// ============================================================================

#include "gpio_config.h"
#include <stddef.h>

const sGpioPinConfig_t g_psGpioPinConfigs[] = {
    {
        .pcPinName = "LED1",
        .eDirection = GPIO_DIR_OUTPUT,
        .ePull = GPIO_PULL_NONE,
        #ifdef PLATFORM_AVR
        .u8AvrPort = 1, // PORTB
        .u8AvrPin = 5,
        #endif
    },
    {
        .pcPinName = "BUTTON1",
        .eDirection = GPIO_DIR_INPUT,
        .ePull = GPIO_PULL_UP,
        #ifdef PLATFORM_AVR
        .u8AvrPort = 1, // PORTB
        .u8AvrPin = 0,
        #endif
    },
    { .pcPinName = NULL } // Terminator
};
